spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbatch?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  type-aliases-package: com.fish.user.bean
server:
  port: 8080